### ISSUE TITLE
I already have installed .NET v6.0 but still I can not install See Through Windows v1.0.7

### ISSUE THREAD

**Issue by X-KRYPTONITE-X** [mobzystems/SeeThroughWindows#4]

**Comment by mobzystems** [comment]
Can you provide al little more information about what it is that actually doesn't work? Do you get an error message during installation, or during startup? If so, which?

**Comment by X-KRYPTONITE-X** [comment]
Here is an attached screenshot given below.
[image: image.png]

**Comment by mobzystems** [comment]
Sorry, but I can't see that image :-/

**Comment by X-KRYPTONITE-X** [comment]
Please check now.

**Comment by X-KRYPTONITE-X** [comment]
Check now please!

**Comment by X-KRYPTONITE-X** [comment]
![image](https://user-images.githubusercontent.com/86785505/152853823-cfc9d249-9392-480f-9ff7-0b34c31bb3ef.png)

**Comment by mobzystems** [comment]
Ha, got it! Thank you. This is a stupid oversight. (In fact a regression - I lost some work, redid it and forgot this part). I (think I) fixed it in the new installer. Could you try it out?

**Comment by X-KRYPTONITE-X** [comment]
> Ha, got it! Thank you. This is a stupid oversight. (In fact a regression - I lost some work, redid it and forgot this part). I (think I) fixed it in the new installer. Could you try it out?

I tried to install it. But still it showing me the same message.
![image](https://user-images.githubusercontent.com/86785505/152984404-1657c072-cd4f-44a7-9f4f-671411502411.png)

**Comment by mobzystems** [comment]
You have to re-download the release, right? I tested the new installer works on a PC without .NET 2.0 and the message is now shown anymore. Just to be sure: please uninstall any version of See Through Windows that you may have installed, then download the new installer https://github.com/mobzystems/SeeThroughWindows/releases/download/1.0.7/SeeThroughWindowsSetup-1.0.7-32bit.msi (maybe clear your browser cache since it's the same file name but a new file) and try again

**Comment by X-KRYPTONITE-X** [comment]
> You have to re-download the release, right? I tested the new installer on a PC without .NET 2.0 and the message is not shown anymore. Just to be sure: please uninstall any version of See Through Windows that you may have installed, then download the new installer https://github.com/mobzystems/SeeThroughWindows/releases/download/1.0.7/SeeThroughWindowsSetup-1.0.7-32bit.msi (maybe clear your browser cache since it's the same file name but a new file) and try again

Thanks a alot sir. It solved. ❤️
