### ISSUE TITLE
Not working with auto-launched Chatterino window

### ISSUE THREAD

**Issue by shatteredhalo** [mobzystems/SeeThroughWindows#5]
Programs used: 
See Through Windows 1.06 64-bit
Streamlink Twitch GUI 2.0.0 32-bit
Chatterino 2.3.4

If I manually open an instance of Chatterino, See Through Windows works as expected: able to make the window transparent using the hot key combo. 

However there is an option in the Streamlink app to automatically launch a chat program of your choice alongside a launched stream, and it is this auto-launched instance of Chatterino that will not go transparent or respond to the See Through Windows hot key combo.

Strangely, this only happens on my Laptop, but on my Desktop PC, the auto-launched Chatterino instance is able to be made transparent without issue.

**Comment by mobzystems** [comment]
See Through Windows is in itself a really simple program. It uses a Windows system function to make complete windows transparent (or undo that). There could be a zillion reasons why that does not work: some windows have a completely custom layout, some are custom-drawn. And then there's the cases (like yours) where it should work but it doesn't.

Long story short: STW is a one trick pony and if its trick doesn't work we don't have the resources to figure out why not. Sorry!
