### ISSUE TITLE
Will be nice to have a reset system for this application xD

### ISSUE THREAD

**Issue by Vittor-Javidan** [mobzystems/SeeThroughWindows#8]
The first time I opened the app, I noticed a dangerous problem. When I assigned a shortcut key to make things see-through, I accidentally started turning other things see-through as well. Eventually, my whole PC was affected by the intended program effect, but without control haha.

Fortunately, the problem was solved by restarting the PC. However, I feel it is very necessary to have a shortcut or something to reset the program effect just in case we lose reference of what is tangible.

**Comment by mobzystems** [comment]
Version 1.0.8 now offers a reset button that restores all transparency. Not a hotkey, though
